#!/bin/sh

set -e

echo "Running postinst for request sink with $1"
if  [ "$1" = configure ]; then
  # creating a link, so the application can be called from the command line
  ln -sf /opt/request-sink/bin/Request-Sink /bin/request-sink
fi

exit 0
