#!/bin/sh

set -e

echo "Running postrm for request sink with $1"
if [ "$1" = 'remove' ]; then
  # remove the installation folder
  rm -rf /opt/request-sink/
  # remove the link in /bin
  rm -f /bin/request-sink
fi

exit 0
