name: Build project with Maven

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The project version to build. It should be equal to the version in the pom.xml file."

jobs:
  verify:
    name: Verify Project before Build
    uses: ./.github/workflows/callable-verify.yaml

  build:
    name: Build DEB package
    needs:
      - verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Set up Just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts bash-completion
      - name: Build and Package
        run: |
          ./mvnw versions:set -DnewVersion="${{ inputs.version }}"
          ./mvnw versions:commit

          CURRENT_DEB_VERSION=$(dpkg-parsechangelog --show-field Version)
          if dpkg --compare-versions "$CURRENT_DEB_VERSION" le "${{ inputs.version }}"; then
            DEBFULLNAME="GitHub Actions"
            DEBEMAIL="tilman@holube.de" 
            dch --newversion ${{ inputs.version }} "Version entry to make sure the package is built with the correct version."
          fi
          
          just deb
      - name: Upload DEB Package
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ./target/request-sink_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error
      - name: Upload App Image
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: ./target/jpackage-image/request-sink/
          retention-days: 1
          overwrite: true
          if-no-files-found: error
