name: Build project with Maven

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The project version to build. It should be equal to the version in the pom.xml file."

jobs:
  verify:
    name: Verify Project before Build
    uses: ./.github/workflows/callable-verify.yaml

  build:
    name: Build DEB package
    needs:
      - verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Set up Just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts bash-completion
      - name: Build and Package
        run: |
          ./mvnw versions:set -DnewVersion="${{ inputs.version }}"
          ./mvnw versions:commit

          CURRENT_DEB_VERSION=$(dpkg-parsechangelog --show-field Version)
          if dpkg --compare-versions "$CURRENT_DEB_VERSION" le "${{ inputs.version }}"; then
            DEBFULLNAME="GitHub Actions"
            DEBEMAIL="tilman@holube.de" 
            dch --newversion ${{ inputs.version }} "Version entry to make sure the package is built with the correct version."
          fi
          
          just deb
      - name: Run Lintian
        run: |
          lintian --version
          lintian --fail-on=error --pedantic --show-overrides ./target/request-sink_${{ inputs.version }}_amd64.deb || true
      - name: Test Installation
        run: |
          sudo apt install -y ./target/request-sink_${{ inputs.version }}_amd64.deb
          request-sink --version
      - name: Test Uninstallation
        run: |
          sudo apt remove -y request-sink
          [ -e "/usr/bin/request-sink" ] && echo "Exiting: /usr/bin/request-sink exists" && exit 1
          [ -d "/usr/lib/request-sink" ] && echo "Exiting: /usr/lib/request-sink exists" && exit 1
          [ -d "/usr/share/doc/request-sink" ] && echo "Exiting: /usr/share/doc/request-sink exists" && exit 1
          [ -d "/usr/share/bash-completion/completions/request-sink" ] && echo "Exiting: /usr/share/bash-completion/completions/request-sink exists" && exit 1
          [ -e "/usr/share/man/man1/request-sink.1.gz" ] && echo "Exiting: /usr/share/man/man1/request-sink.1.gz exists" && exit 1

          echo "Uninstallation test passed successfully."
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ./target/request-sink_${{ inputs.version }}_amd64.deb
          retention-days: 1
          overwrite: true
          if-no-files-found: error
