name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-version-string:
    name: "Create Version String from Tag"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - id: step1
        run: |
          version=$(echo "${{ github.ref_name }}" | cut -c 2-)
          echo "${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

  build:
    uses: ./.github/workflows/callable-build.yaml
    with:
      version: ${{ needs.create-version-string.outputs.version }}
    secrets: inherit

  release-to-github:
    needs:
      - build
      - create-version-string
    uses: ./.github/workflows/release-gh.yaml
    with:
      tag: ${{ github.ref_name }}
      prerelease: false
    secrets: inherit

  release-to-ppa:
    needs:
      - build
      - create-version-string
    uses: ./.github/workflows/release-ppa.yaml
